import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';
export async function phase5Checks({db,rpc,asUser,scalar,test,admin,c,b,owner,reviewer,outsider,role,currency,supplier}){
 const ids=(await db.query("select id from public.permissions where active and resource in ('bank','payment_order','payment','payment_batch','bank_transaction','bank_reconciliation','cashflow')")).rows.map(x=>x.id);
 const old=(await db.query('select permission_id from public.role_permissions where role_id=$1',[role.id])).rows.map(x=>x.permission_id);
 await rpc(admin,'admin_set_role_permissions',[role.id,[...new Set([...old,...ids])]]);await rpc(admin,'admin_set_user_role',[outsider,role.id,c,true]);
 const reconciler=randomUUID();await db.query('insert into auth.users values($1,$2)',[reconciler,'reconciler@example.test']);await db.query('insert into auth.sessions values($1,$1)',[reconciler]);await db.query("insert into public.profiles(id,email,username,full_name,status) values($1,'reconciler@example.test','reconciler','Synthetic reconciler','active')",[reconciler]);await rpc(admin,'admin_set_membership',[reconciler,c,true]);await rpc(admin,'admin_set_user_role',[reconciler,role.id,c,true]);
 const save=(u,k,p,id=null,company=c)=>rpc(u,'treasury_save',[k,id,company,p]);const act=(u,k,id,a,p={})=>rpc(u,'treasury_action',[k,id,a,p]);
 const payables=(await db.query("select * from public.payables where company_id=$1 and status='approved' order by id",[c])).rows;
 const bank=await save(owner,'bank',{code:'SYN',name:'Banco sintético'});const account=await save(owner,'bank_account',{bank_id:bank.id,currency_id:currency,account_number:'123456789',display_name:'Cuenta sintética',opening_balance:500,opening_date:'2026-09-01',valid_from:'2026-09-01'});
 const method=await save(owner,'payment_method',{code:'transfer',name:'Transferencia',requires_beneficiary_account:true});const beneficiary=await scalar("select id from public.supplier_bank_accounts where company_id=$1 and status='active'",[c]);
 const orderBase={beneficiary_id:supplier.supplier_id,currency_id:currency,payment_method_id:method.id,beneficiary_account_id:beneficiary,requested_payment_date:'2026-09-11',description:'Orden sintética',items:payables.map(p=>({payable_id:p.id,amount_to_pay:Number(p.outstanding_amount)}))};let order,payment,second,batch,transaction,period,match;
 async function voucher(pay){const a=await rpc(outsider,'attachment_prepare_versioned',[c,'payment',pay.id,'voucher.pdf','application/pdf',10,'V1']);await asUser(outsider,'insert into storage.objects(bucket_id,name,metadata) values($1,$2,$3)',['financial-encrypted',a.storage_path,{size:42,mimetype:'application/octet-stream'}]);await rpc(outsider,'attachment_finish',[a.id]);return a;}
 await test('F5 banks scoped and no automatic financial administrator grants',async()=>{await assert.rejects(()=>save(owner,'bank_account',{bank_id:bank.id,currency_id:currency,account_number:'999999999',display_name:'Wrong'},null,b));assert.equal(await rpc(admin,'has_permission',['payment.execute',c]),false);});
 await test('F5 OP multiple payables, outstanding and currency validation',async()=>{await assert.rejects(()=>save(owner,'payment_order',{...orderBase,items:[{payable_id:payables[0].id,amount_to_pay:1000}]}),/outstanding/);const usd=await scalar("select id from public.currencies where code='USD'");await assert.rejects(()=>save(owner,'payment_order',{...orderBase,currency_id:usd}),/Incompatible/);order=await save(owner,'payment_order',orderBase);assert.equal(Number(order.total_amount),200);assert.match(order.payment_order_number,/OP-/);});
 await test('F5 reservations, segregation, approved immutability and scheduling',async()=>{await act(owner,'payment_order',order.id,'submit');await assert.rejects(()=>act(owner,'payment_order',order.id,'approve'),/self approval/);await act(reviewer,'payment_order',order.id,'approve');await assert.rejects(()=>save(owner,'payment_order',{description:'Changed'},order.id),/immutable/);await act(outsider,'payment_order',order.id,'schedule',{bank_account_id:account.id,scheduled_payment_date:'2026-09-11'});const competing=await save(owner,'payment_order',orderBase);await assert.rejects(()=>act(owner,'payment_order',competing.id,'submit'),/unreserved/);});
 await test('F5 batch requires individual approvals and independent actor',async()=>{batch=await save(owner,'payment_batch',{currency_id:currency,description:'Lote',order_ids:[order.id],individual_approval_required:true});await act(owner,'payment_batch',batch.id,'submit');await assert.rejects(()=>act(owner,'payment_batch',batch.id,'approve'),/self approval/);await act(reviewer,'payment_batch',batch.id,'approve');});
 await test('F5 partial payment requires encrypted voucher, active membership and segregation',async()=>{const input={payment_order_id:order.id,payment_date:'2026-09-11',operation_number:'PART1',allocations:[{payable_id:payables[0].id,allocated_amount:60}]};await assert.rejects(()=>save(owner,'payment',input),/segregation/);payment=await save(outsider,'payment',input);await assert.rejects(()=>act(outsider,'payment',payment.id,'execute'),/Voucher/);const a=await voucher(payment);await rpc(admin,'admin_set_membership',[outsider,c,false]);assert.equal((await asUser(outsider,'select * from public.attachments where id=$1',[a.id])).rows.length,0);await rpc(admin,'admin_set_membership',[outsider,c,true]);await act(outsider,'payment',payment.id,'execute');assert.equal(Number(await scalar('select outstanding_amount from public.payables where id=$1',[payables[0].id])),40);});
 await test('F5 full payment covers several payables; paid is derived not assignable',async()=>{second=await save(outsider,'payment',{payment_order_id:order.id,payment_date:'2026-09-11',operation_number:'PART2',allocations:[{payable_id:payables[0].id,allocated_amount:40},{payable_id:payables[1].id,allocated_amount:100}]});await voucher(second);await act(outsider,'payment',second.id,'execute');assert.equal(await scalar('select payment_status from public.payables where id=$1',[payables[0].id]),'paid');assert.equal(await scalar('select status from public.payment_orders where id=$1',[order.id]),'paid');await assert.rejects(()=>asUser(owner,"update public.payables set outstanding_amount=0"),/permission denied/);});
 await test('F5 reversal restores balances, preserves original and inverse expected movement',async()=>{await act(reviewer,'payment',second.id,'reverse',{reason:'Registro sintético corregido'});assert.equal(Number(await scalar('select outstanding_amount from public.payables where id=$1',[payables[0].id])),40);assert.equal(await scalar("select count(*)::int from public.bank_transactions where payment_id=$1",[second.id]),2);assert.equal(await scalar('select status from public.payments where id=$1',[second.id]),'reversed');});
 const rows=[{transaction_date:'2026-09-11',transaction_type:'debit',amount:60,currency_code:'PEN',bank_reference:'PART1',description:'Extracto sintético',external_id:'ROW1'}];
 await test('F5 bank import preview no persistence, transaction idempotence and expected distinction',async()=>{const before=await scalar('select count(*)::int from public.bank_transactions');const preview=await rpc(owner,'treasury_import',[c,account.id,'synthetic.csv',{},rows,false]);assert.equal(preview.status,'preview');assert.equal(await scalar('select count(*)::int from public.bank_transactions'),before);const result=await rpc(owner,'treasury_import',[c,account.id,'synthetic.csv',{},rows,true]);assert.equal(result.inserted,1);assert.equal((await rpc(owner,'treasury_import',[c,account.id,'synthetic.csv',{},rows,true])).status,'already_imported');transaction=await scalar("select id from public.bank_transactions where bank_account_id=$1 and external_id='ROW1'",[account.id]);});
 await test('F5 candidates are suggestions, matching rejects foreign scope and executor',async()=>{const candidates=await rpc(owner,'treasury_candidates',[c,transaction]);assert.ok(candidates.some(p=>p.id===payment.id));period=await save(owner,'reconciliation_period',{bank_account_id:account.id,start_date:'2026-09-01',end_date:'2026-09-30'});await assert.rejects(()=>rpc(reconciler,'treasury_match',[b,period.id,transaction,payment.id,60]));await assert.rejects(()=>rpc(outsider,'treasury_match',[c,period.id,transaction,payment.id,60]),/Executor/);match=await rpc(reconciler,'treasury_match',[c,period.id,transaction,payment.id,60]);assert.equal(match.status,'matched');});
 await test('F5 reconcile, close, immutable period, controlled reopening and reverse protection',async()=>{await act(reconciler,'reconciliation_match',match.id,'reconcile');await act(reconciler,'reconciliation_period',period.id,'close');await assert.rejects(()=>act(reviewer,'payment',payment.id,'reverse',{reason:'Test'}),/Reopen and unmatch/);await assert.rejects(()=>act(reconciler,'reconciliation_match',match.id,'unmatch',{reason:'Test'}),/Closed/);await act(reconciler,'reconciliation_period',period.id,'reopen',{reason:'Corrección auditada'});});
 await test('F5 cashflow counts imported actual once and outstanding committed once',async()=>{const flow=await rpc(owner,'treasury_cashflow',[c]);assert.equal(Number(flow.actual[0].amount),-60);assert.equal(flow.committed.reduce((n,p)=>n+Number(p.amount),0),140);assert.equal(Number(flow.position[0].recorded_position),440);assert.deepEqual(flow.forecast,[]);});
 await test('F5 REST writes blocked and audit contains company, actor, no full bank account',async()=>{await assert.rejects(()=>asUser(outsider,"update public.payments set status='executed'"),/permission denied/);const audit=(await db.query("select * from public.audit_logs where entity_type='company_bank_accounts' and company_id=$1",[c])).rows;assert.ok(audit.length);assert.ok(audit.every(e=>e.user_id&&e.company_id===c&&!e.new_values?.account_number));});
 await test('F5 direct RPC rejects NaN and silent monetary rounding; core entry points are private',async()=>{await assert.rejects(()=>save(owner,'bank_transaction',{bank_account_id:account.id,transaction_date:'2026-09-11',transaction_type:'credit',amount:'NaN',bank_reference:'INVALID',description:'Invalid'}),/JSON numbers/);await assert.rejects(()=>save(owner,'bank_transaction',{bank_account_id:account.id,transaction_date:'2026-09-11',transaction_type:'credit',amount:0.001,bank_reference:'INVALID',description:'Invalid'}),/precision/);await assert.rejects(()=>rpc(owner,'treasury_save_v5_core',['bank',null,c,{code:'BYPASS',name:'Forbidden'}]),/permission denied/);});

}
