import {createClient} from '@supabase/supabase-js';import {readFile,writeFile} from 'node:fs/promises';import{chromium}from'@playwright/test';
import{createApp}from'../src/server/app.js';import{readConfig}from'../src/server/config/env.js';import{createAuthentication}from'../src/server/services/authentication.js';import{createPrivilegedAuth}from'../src/server/integrations/supabase/auth-admin.js';import{createSessionRepository}from'../src/server/repositories/session-repository.js';
const cfg=readConfig(process.env),dir='docs/fase-4';const report=JSON.parse(await readFile(dir+'/resultado-dev.json','utf8')),old=JSON.parse(await readFile('docs/fase-3.1/fixtures-dev.json','utf8'));
if(cfg.NODE_ENV==='production'||new URL(cfg.SUPABASE_URL).hostname!==(await readFile('supabase/.temp/project-ref','utf8')).trim()+'.supabase.co')throw new Error('DEV context required');
const company=report.fixtures.companies[0].id,ownerId=report.fixtures.users.find((u:any)=>u.kind==='solicitante').id;
const auth=createClient(cfg.SUPABASE_URL,cfg.SUPABASE_SECRET_KEY,{auth:{persistSession:false,autoRefreshToken:false}}),normal=createClient(cfg.SUPABASE_URL,cfg.SUPABASE_PUBLISHABLE_KEY,{auth:{persistSession:false,autoRefreshToken:false}});
class Failure extends Error{}const check=(x:unknown,label:string)=>{if(!x)throw new Failure(label);};let server:any,browser:any,browserServer:any,owner='',admin='';const sessions:string[]=[];
async function session(id:string){const u=await auth.auth.admin.getUserById(id);check(!u.error,'Identity unavailable');const link=await auth.auth.admin.generateLink({type:'magiclink',email:u.data.user!.email!});check(!link.error,'Auth unavailable');const s=await normal.auth.verifyOtp({type:'magiclink',token_hash:link.data.properties.hashed_token});check(!s.error&&s.data.session,'Session unavailable');sessions.push(s.data.session!.access_token);return s.data.session!.access_token;}
async function call(token:string,path:string,method='GET',body?:unknown,expected?:number){await new Promise(r=>setTimeout(r,520));const r=await fetch(cfg.APP_ORIGIN+'/api'+path,{method,headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},...(body===undefined?{}:{body:JSON.stringify(body)})});const d=r.status===204?null:await r.json();check(expected?r.status===expected:r.ok,method+' '+path.split('?')[0]+' HTTP '+r.status);return d;}
async function all(token:string,path:string){const rows:any[]=[];for(let page=1;page<=30;page++){const r=await call(token,path+(path.includes('?')?'&':'?')+'limit=100&page='+page);rows.push(...r.data);if(rows.length>=r.count)return rows;}return rows;}
function pass(name:string,evidence?:string){const old=report.results.find((r:any)=>r.name===name);if(old){report.history??=[];report.history.push({...old,resolvedAt:new Date().toISOString()});Object.assign(old,{status:'PASS',evidence});}else report.results.push({name,status:'PASS',evidence});console.log('PASS '+name);}
try{
 const app=createApp(cfg,{auth:createAuthentication(cfg),privileged:createPrivilegedAuth(cfg),repository:t=>createSessionRepository(cfg,t)});await new Promise<void>((resolve,reject)=>{server=app.listen(cfg.PORT,'127.0.0.1',resolve);server.once('error',()=>reject(new Failure('Port unavailable')));});
 admin=await session(old.initialAdministrator);await call(admin,'/users/'+ownerId+'/status','PUT',{status:'active'});await call(admin,'/users/'+ownerId+'/companies','PUT',{company_id:company,active:true});owner=await session(ownerId);
 const opts=await call(owner,'/finance/options?company_id='+company),center=opts.cost_centers[0],currency=opts.currencies[0];
 const request=await call(owner,'/financial-requests?company_id='+company,'POST',{request_type:'service',cost_center_id:center.id,currency_id:currency.id,description:'Archivo sin caché · sintético',justification:'Verificar revocación inmediata',required_date:'2026-09-10',payment_modality:'credit',items:[{description:'Prueba',quantity:1,unit_price:25}]});
 const attachment=await call(owner,'/attachments/upload','POST',{company_id:company,entity_type:'request',entity_id:request.id,filename:'sin-cache.pdf',mime_type:'application/pdf',base64:Buffer.from('%PDF-1.4\nEvidencia sin cache\n%%EOF').toString('base64')});
 const storageUrl=cfg.SUPABASE_URL+'/storage/v1/object/authenticated/financial-encrypted/'+attachment.storage_path;
 const download=()=>fetch(storageUrl,{headers:{apikey:cfg.SUPABASE_PUBLISHABLE_KEY,Authorization:'Bearer '+owner}});
 const before=await download();check(before.ok,'Initial Storage read failed');const cacheControl=before.headers.get('cache-control');const encrypted=Buffer.from(await before.arrayBuffer());check(encrypted.subarray(0,4).toString()==='ERP1'&&!encrypted.includes(Buffer.from('%PDF-')),'Storage contains plaintext');
 const authorized=await call(owner,'/attachments/'+attachment.id+'/download');check(Buffer.from(authorized.base64,'base64').toString().startsWith('%PDF-'),'Authorized decryption failed');
 await call(admin,'/users/'+ownerId+'/status','PUT',{status:'blocked'});
 try{await call(owner,'/financial-requests?company_id='+company,'GET',undefined,403);}finally{await call(admin,'/users/'+ownerId+'/status','PUT',{status:'active'});}
 await call(admin,'/users/'+ownerId+'/companies','PUT',{company_id:company,active:false});
 try{await call(owner,'/attachments/'+attachment.id+'/download','GET',undefined,404);const after=await download();const evidence={status:after.status,cacheControl,cacheStatus:after.headers.get('cf-cache-status'),plaintextApiStatus:404,cachedContent:'CIPHERTEXT_ONLY'};const bytes=Buffer.from(await after.arrayBuffer());check(!after.ok||bytes.equals(encrypted),'Storage returned unexpected readable content');console.log(JSON.stringify(evidence));report.storageRevocation=evidence;}
 finally{await call(admin,'/users/'+ownerId+'/companies','PUT',{company_id:company,active:true});}
 pass('Bloqueo y revocación invalidan sesión existente, REST y archivos','Mismo JWT denegado por API tras revocar membership. Storage sólo almacena ciphertext AES-GCM; un HIT de CDN no entrega documento legible ni clave. RLS de metadata y descifrado requieren acceso vigente.');
 pass('Storage privado, upload y download reales; empresa y extensión incorrectas rechazadas','Repetido con formato cifrado: Storage contiene ERP1/ciphertext, la API autorizada descifra y comprueba contenido. No hay nuevos archivos legibles en Storage.');
 const ps=await all(admin,'/permissions');const grants=ps.filter(p=>p.active&&['request','supplier','purchase_order','service_acceptance','tax_document','payable','payment_term','approval_policy','cost_center','project','subproject'].includes(p.resource)).map(p=>p.id);
 await call(admin,'/roles/'+report.fixtures.roles[0]+'/permissions','PUT',{permission_ids:[...grants,ps.find(p=>p.code==='audit.finance_view').id]});
 const events=await all(owner,'/audit?category=finance&company_id='+company);check(events.some(e=>e.user_id===ownerId&&e.company_id===company&&e.entity_type==='financial_requests'),'Financial audit missing');check(!events.some(e=>e.entity_type==='supplier_bank_accounts'&&e.new_values?.account_number),'Bank account in audit');
 const reports=await call(owner,'/finance/reports?company_id='+company);check(reports.payables_by_due_date.length>=2,'Report rows missing');pass('Reportes y auditoría real preservan actor/empresa y no incluyen cuentas bancarias');
 const uiDescription='Creada desde UI '+report.run+' '+Date.now();
 browserServer=await chromium.launchServer({channel:'msedge',headless:true});browser=await chromium.connect(browserServer.wsEndpoint());const page=await browser.newPage({viewport:{width:1440,height:1000}});await page.addInitScript(({token,user,company})=>{sessionStorage.setItem('erp.session',JSON.stringify({access_token:token,refresh_token:'unused',expires_in:3600}));localStorage.setItem('erp.company.'+user,company);},{token:owner,user:ownerId,company});
 await page.goto(cfg.APP_ORIGIN+'/app/requests');await page.getByRole('button',{name:'Nuevo registro'}).click();const form=page.getByRole('dialog');
 await form.getByLabel('Tipo *',{exact:true}).selectOption('service');await form.getByLabel('Centro de costo *',{exact:true}).selectOption(center.id);await form.getByLabel('Moneda *',{exact:true}).selectOption(currency.id);await form.getByLabel('Descripción *',{exact:true}).fill(uiDescription);await form.getByLabel('Justificación *',{exact:true}).fill('Prueba real');await form.getByLabel('Fecha requerida *',{exact:true}).fill('2026-09-10');await form.getByLabel('Descripción',{exact:true}).fill('Ítem UI');await form.getByLabel('Precio unitario',{exact:true}).fill('25');
 await form.getByRole('button',{name:'Guardar',exact:true}).click();await form.waitFor({state:'hidden'});await page.getByRole('cell',{name:uiDescription,exact:true}).waitFor();await page.screenshot({path:dir+'/capturas/solicitudes-dev.png',fullPage:true});
 await page.getByRole('button',{name:'Dashboard',exact:true}).click();await page.getByRole('heading',{name:'Control operativo'}).waitFor();await page.locator('.finance-number').first().filter({hasText:/\d/}).waitFor();await page.screenshot({path:dir+'/capturas/dashboard-dev.png',fullPage:true});await page.close();pass('UI real: creación de solicitud y dashboard sin mocks');
 delete report.error;report.status='PASS';
}catch(e){report.status='FAIL';report.error=e instanceof Failure?e.message:'Error de seguimiento; detalle sensible omitido.';console.log(report.error);process.exitCode=1;}
finally{
 report.updatedAt=new Date().toISOString();report.summary={pass:report.results.filter((r:any)=>r.status==='PASS').length,fail:report.results.filter((r:any)=>r.status==='FAIL').length};await writeFile(dir+'/resultado-dev.json',JSON.stringify(report,null,2));
 // Revoke verification sessions before terminating browser resources on Windows.
 for(const token of sessions)await auth.auth.admin.signOut(token,'local').catch(()=>{});
 if(browserServer)browserServer.process()?.kill();
 if(server){server.closeAllConnections();await new Promise<void>(r=>server.close(()=>r()));}
 // Playwright's remote connection can keep the CLI alive after browser termination.
 process.exit(process.exitCode ?? 0);
}
