import {createClient} from '@supabase/supabase-js';
import {Client} from 'pg';
import {randomUUID,randomBytes} from 'node:crypto';
import {readFile,writeFile,mkdir,readdir} from 'node:fs/promises';
import {existsSync} from 'node:fs';
import {loadEnvFile} from 'node:process';
import {chromium} from '@playwright/test';
import ExcelJS from 'exceljs';
import {createApp} from '../src/server/app.js';
import {readConfig} from '../src/server/config/env.js';
import {createAuthentication} from '../src/server/services/authentication.js';
import {createPrivilegedAuth} from '../src/server/integrations/supabase/auth-admin.js';
import {createSessionRepository} from '../src/server/repositories/session-repository.js';

// Explicitly authorized DEV verification. Never print SDK errors, response bodies, identities or credentials.
if(existsSync('.env.verification.local'))loadEnvFile('.env.verification.local');
const titles=['Migraciones 001–011','Variables backend','Separación publishable/secret','Administrador inicial','Dos empresas de prueba','Usuarios solicitante/aprobador/Finanzas/administrador','Memberships empresariales','Roles por empresa','Selector multiempresa','CECO raíz e hijo','Rechazo de ciclo CECO','Rechazo de padre de otra empresa','Proyecto/subproyecto','CSV y XLSX contra API real','Preview sin persistencia','Confirmación de importación','Idempotencia al repetir lote','Bloqueo con sesión existente','Revocación de membership con sesión existente','REST directo a tablas','Auditoría','SMTP y callback','Ausencia de secret en bundle/logs'];
const critical=new Set([1,2,3,4,7,8,9,11,12,15,17,18,19,20,21,23]);
const results=titles.map((name,i)=>({id:i+1,name,critical:critical.has(i+1),status:'BLOCKED_EXTERNAL',evidence:'Dependencia todavía no verificada.'}));
class Failure extends Error{}class Blocked extends Error{}
const check=(condition:unknown,label:string)=>{if(!condition)throw new Failure(label);};
async function run(id:number,fn:()=>Promise<string>){try{results[id-1]!.evidence=await fn();results[id-1]!.status='PASS';}catch(e){results[id-1]!.status=e instanceof Blocked?'BLOCKED_EXTERNAL':'FAIL';results[id-1]!.evidence=e instanceof Failure||e instanceof Blocked?e.message:'Operación fallida; detalle sensible omitido. Revisar diagnóstico controlado.';}console.log(`${id}: ${results[id-1]!.status}`);await persist();}
const folder='docs/fase-3.1';const tag='V31_'+new Date().toISOString().replace(/\D/g,'').slice(0,14);const manifest:any={run:tag,createdAt:new Date().toISOString(),companies:[],users:[],roles:[]};
let server:any,browser:any,sql:Client|undefined;let base='',adminToken='';const logs:string[]=[];let config:any;
let apiCalls=0;const snapshots:any={};
async function persist(){await mkdir(folder,{recursive:true});const summary={criticalPass:results.filter(r=>r.critical&&r.status==='PASS').length,criticalFail:results.filter(r=>r.critical&&r.status==='FAIL').length,blockedExternal:results.filter(r=>r.status==='BLOCKED_EXTERNAL').length,pass:results.filter(r=>r.status==='PASS').length,fail:results.filter(r=>r.status==='FAIL').length};await writeFile(`${folder}/resultado-dev.json`,JSON.stringify({run:tag,generatedAt:new Date().toISOString(),summary,results},null,2));await writeFile(`${folder}/fixtures-dev.json`,JSON.stringify(manifest,null,2));await writeFile(`${folder}/resultado-dev.md`,['# Fase 3.1 — Verificación Supabase DEV real','',`Ejecución: ${tag}. Actualización: ${new Date().toISOString()}.`,'','Sólo datos sintéticos. No se repitieron migraciones ni bootstrap. No se inició Fase 4.','',`Critical PASS: **${summary.criticalPass}** · Critical FAIL: **${summary.criticalFail}** · BLOCKED_EXTERNAL: **${summary.blockedExternal}**`,'',`PASS totales: ${summary.pass} · FAIL totales: ${summary.fail}. Los bloqueos externos no se cuentan como pruebas aprobadas.`,'','| N.º | Caso | Crítico | Resultado | Evidencia |','|---|---|---|---|---|',...results.map(r=>`| ${r.id} | ${r.name} | ${r.critical?'Sí':'No'} | ${r.status} | ${r.evidence.replaceAll('|','/')} |`),'','Los identificadores de fixtures quedan en fixtures-dev.json para revisión. Las contraseñas y sesiones se generan en memoria y no se guardan. No se realizan limpiezas destructivas.'].join('\n'));}
async function api(path:string,method='GET',body?:any,token=adminToken){apiCalls++;const r=await fetch(base+'/api'+path,{method,headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{}),'Idempotency-Key':randomUUID()},...(body===undefined?{}:{body:JSON.stringify(body)}),signal:AbortSignal.timeout(20000)});let data:any=null;if(r.status!==204){try{data=await r.json();}catch{}}return {status:r.status,data};}
async function ok(path:string,method='GET',body?:any,token=adminToken){const r=await api(path,method,body,token);check(r.status>=200&&r.status<300,`HTTP ${r.status} en ${path.split('?')[0]} (${r.data?.error&&/^[A-Z_]+$/.test(r.data.error)?r.data.error:'respuesta no exitosa'}).`);return r.data;}
async function rest(path:string,method:string,body:any,token:string,key=config.SUPABASE_PUBLISHABLE_KEY){const r=await fetch(config.SUPABASE_URL+'/rest/v1/'+path,{method,headers:{apikey:key,Authorization:'Bearer '+token,'Content-Type':'application/json'},...(body===undefined?{}:{body:JSON.stringify(body)}),signal:AbortSignal.timeout(15000)});let data:any;try{data=await r.json();}catch{}return {status:r.status,data};}
async function list(path:string,token=adminToken){const rows:any[]=[];for(let page=1;page<=100;page++){const r=await ok(path+(path.includes('?')?'&':'?')+'limit=100&page='+page,'GET',undefined,token);rows.push(...r.data);if(rows.length>=r.count)return rows;}throw new Failure('Catálogo excede el límite de verificación.');}
const pause=()=>new Promise(resolve=>setTimeout(resolve,1100));
let finance:any,solicitante:any,approver:any,A:any,B:any,root:any,child:any,foreign:any;
try{
 await run(2,async()=>{config=readConfig(process.env);check(new URL(config.APP_ORIGIN).hostname==='localhost'||new URL(config.APP_ORIGIN).hostname==='127.0.0.1','El origen de verificación debe ser loopback.');check(config.NODE_ENV!=='production','Se requiere NODE_ENV de desarrollo.');return 'Variables backend válidas, cargadas localmente sin imprimir valores. Entorno confirmado DEV por el propietario.';});
 if(!config)throw new Blocked('Configuración backend no válida.');
 await run(1,async()=>{if(!process.env.SUPABASE_DB_URL)throw new Blocked('Falta .env.verification.local / SUPABASE_DB_URL en esta ubicación. No se repitieron migraciones.');sql=new Client({connectionString:process.env.SUPABASE_DB_URL,connectionTimeoutMillis:15000,query_timeout:15000});await sql.connect();const q=await sql.query("select version from supabase_migrations.schema_migrations order by version");const versions=q.rows.map(r=>String(r.version));check(Array.from({length:11},(_,i)=>'20260909'+String(i+1).padStart(4,'0')).every(v=>versions.includes(v)),'El historial remoto no acredita todas las migraciones 001–011.');const rls=await sql.query("select count(*)::int n from pg_tables where schemaname='public' and rowsecurity");check(rls.rows[0].n>=18,'Faltan tablas con RLS.');return 'Historial remoto 001–011 y RLS consultados en modo lectura; no se ejecutó DDL.';});
 const privileged=createClient(config.SUPABASE_URL,config.SUPABASE_SECRET_KEY,{auth:{persistSession:false,autoRefreshToken:false},global:{fetch:(u,o)=>fetch(u,{...o,signal:AbortSignal.timeout(15000)})}});
 const auth=createAuthentication(config);const normal=createClient(config.SUPABASE_URL,config.SUPABASE_PUBLISHABLE_KEY,{auth:{persistSession:false,autoRefreshToken:false}});
 const app=createApp(config,{auth,privileged:createPrivilegedAuth(config),repository:t=>createSessionRepository(config,t)});
 await new Promise<void>((resolve,reject)=>{server=app.listen(config.PORT,'127.0.0.1',resolve);server.once('error',()=>reject(new Blocked('Puerto local ocupado o inaccesible.')));});base=config.APP_ORIGIN;
 await run(3,async()=>{check(config.SUPABASE_PUBLISHABLE_KEY.startsWith('sb_publishable_')&&config.SUPABASE_SECRET_KEY.startsWith('sb_secret_'),'Formato de claves incorrecto.');const denied=await rest('rpc/resolve_login_username','POST',{login_name:'not-an-identity'},'',config.SUPABASE_PUBLISHABLE_KEY);check([401,403].includes(denied.status),'Lookup privilegiado accesible con publishable sin sesión.');const {error}=await privileged.auth.admin.listUsers({page:1,perPage:1});check(!error,'Auth Admin no acepta la clave backend.');return 'Auth Admin acepta secret; publishable sin sesión no ejecuta lookup privilegiado. CRUD de pruebas usa API request-scoped.';});
 await run(4,async()=>{const users=await privileged.auth.admin.listUsers({page:1,perPage:100});check(!users.error,'No se pudo consultar Auth Admin.');let initial=users.data.users.filter(u=>!u.email?.includes('v31_'));if(sql){const admin=await sql.query("select p.id from public.profiles p join public.user_roles ur on ur.user_id=p.id join public.roles r on r.id=ur.role_id where r.code='system_administrator' and p.status='active' and ur.company_id is null limit 1");initial=users.data.users.filter(u=>u.id===admin.rows[0]?.id);}if(initial.length!==1)throw new Blocked('No se puede identificar inequívocamente el administrador inicial sin acceso SQL.');const generated=await privileged.auth.admin.generateLink({type:'magiclink',email:initial[0]!.email!});check(!generated.error,'No se pudo preparar sesión de verificación del administrador.');const verified=await normal.auth.verifyOtp({token_hash:generated.data.properties.hashed_token,type:'magiclink'});check(!verified.error&&verified.data.session,'No se pudo verificar sesión Auth real.');adminToken=verified.data.session!.access_token;const me=await ok('/auth/me');check(me.profile.status==='active'&&me.permissions.some((p:any)=>p.code==='role.assign'),'Administrador no efectivo.');manifest.initialAdministrator=me.profile.id;return 'Administrador existente activo y efectivo, autenticado con sesión real. Bootstrap no repetido; contraseña no modificada.';});
 if(!adminToken)throw new Blocked('No hay sesión administrativa verificada.');
 await run(5,async()=>{for(const suffix of ['A','B']){const c=await ok('/companies','POST',{code:tag+'_'+suffix,legal_name:`VERIFICACIÓN DEV ${tag} EMPRESA ${suffix}`,tax_id:tag+'_'+suffix,country_code:'PE'});manifest.companies.push({id:c.id,code:c.code});if(suffix==='A')A=c;else B=c;}return 'Dos empresas sintéticas creadas por Express/RPC; identificadas en el manifiesto.';});
 await run(6,async()=>{for(const kind of ['solicitante','aprobador','finanzas']){const username=(tag+'_'+kind).toLowerCase();const user=await ok('/users','POST',{email:username+'@example.com',username,full_name:'PRUEBA DEV '+kind+' '+tag,status:'active'});const password=randomBytes(30).toString('base64url')+'aA7!';const changed=await privileged.auth.admin.updateUserById(user.id,{password,email_confirm:true});check(!changed.error,'No se pudo preparar contraseña de una identidad sintética.');const login=await ok('/auth/login','POST',{email:username,password},'');const record={...user,password,token:login.access_token};manifest.users.push({id:user.id,username,kind});if(kind==='finanzas')finance=record;else if(kind==='solicitante')solicitante=record;else approver=record;}return 'Tres usuarios sintéticos provisionados por API y login por username real; administrador inicial conservado.';});
 if(!finance||!solicitante||!A||!B)throw new Blocked('Fixtures de identidad/empresas incompletos.');
 await run(7,async()=>{for(const [u,c] of [[solicitante,A],[approver,A],[finance,A],[finance,B]])await ok(`/users/${u.id}/companies`,'PUT',{company_id:c.id,active:true});const w=await ok('/auth/workspace','GET',undefined,solicitante.token);check(w.companies.length===1&&w.companies[0].id===A.id,'Membresías no aisladas.');return 'Solicitante/aprobador en A; Finanzas en A/B. Workspace del solicitante excluye B.';});
 await run(8,async()=>{const permissions=await list('/permissions');for(const [kind,user,codes] of [['sol',solicitante,['cost_center.view','project.view']],['apr',approver,['cost_center.view']],['fin',finance,['cost_center.view','cost_center.create','cost_center.edit','cost_center.disable','project.view','project.create','project.edit','subproject.view','subproject.create','subproject.edit']]] as any[]){const role=await ok('/roles','POST',{code:(tag+'_'+kind).toLowerCase(),name:'VERIFICACIÓN '+tag+' '+kind});await ok(`/roles/${role.id}/permissions`,'PUT',{permission_ids:permissions.filter((p:any)=>codes.includes(p.code)).map((p:any)=>p.id)});await ok(`/users/${user.id}/roles`,'PUT',{role_id:role.id,company_id:A.id,assign:true});if(kind==='fin')await ok(`/users/${user.id}/roles`,'PUT',{role_id:role.id,company_id:B.id,assign:true});manifest.roles.push({id:role.id,kind});}const x=await rest('rpc/has_permission','POST',{permission_code:'cost_center.view',company_id:B.id},solicitante.token);check(x.status===200&&x.data===false,'Permisos A autorizan B.');return 'Roles nuevos configurados y asignados por empresa; permiso A no concede B. Sin grants financieros nuevos.';});
 await run(9,async()=>{browser=await chromium.launch({channel:'msedge',headless:true});const page=await browser.newPage();await page.goto(base+'/login');await page.getByLabel('Correo o usuario').fill(finance.username);await page.getByLabel('Contraseña',{exact:true}).fill(finance.password);await page.getByRole('button',{name:'Ingresar a la plataforma'}).click();await page.getByRole('heading',{name:'Su espacio de gestión'}).waitFor();await page.getByLabel('Empresa activa',{exact:true}).selectOption(B.id);await page.getByRole('heading',{name:B.legal_name,exact:true}).waitFor();await page.getByLabel('Empresa activa',{exact:true}).selectOption(A.id);await page.getByRole('heading',{name:A.legal_name,exact:true}).waitFor();await page.close();return 'Navegador real sin mocks: login y cambio B→A confirmados visualmente contra API DEV.';});
 await run(10,async()=>{root=await ok('/cost-centers?company_id='+A.id,'POST',{code:tag+'_ROOT',name:'Raíz DEV'},finance.token);child=await ok('/cost-centers?company_id='+A.id,'POST',{code:tag+'_CHILD',name:'Hijo DEV',parent_id:root.id},finance.token);check(child.level===1,'Nivel de hijo incorrecto.');return 'Raíz e hijo persistidos en DEV; nivel derivado 0/1.';});
 await run(11,async()=>{check(root&&child,'Faltan CECO de prueba.');const r=await api('/cost-centers/'+root.id+'?company_id='+A.id,'PATCH',{parent_id:child.id},finance.token);check(r.status===409,'Ciclo no rechazado con 409.');const rows=await list('/cost-centers?company_id='+A.id,finance.token);check(rows.find((r:any)=>r.id===root.id)?.parent_id===null,'El rechazo dejó una mutación.');return 'Ciclo rechazado HTTP 409; padre original conserva NULL.';});
 await run(12,async()=>{foreign=await ok('/cost-centers?company_id='+B.id,'POST',{code:tag+'_BROOT',name:'Raíz empresa B'},finance.token);const r=await api('/cost-centers/'+child.id+'?company_id='+A.id,'PATCH',{parent_id:foreign.id},finance.token);check(r.status===409,'Padre de otra empresa no rechazado.');return 'Referencia A→B rechazada HTTP 409 por la regla persistida.';});
 await run(13,async()=>{const p=await ok('/projects?company_id='+A.id,'POST',{code:tag+'_P',name:'Proyecto DEV'},finance.token);const s=await ok('/subprojects?company_id='+A.id,'POST',{code:tag+'_S',name:'Subproyecto DEV',project_id:p.id},finance.token);check(s.company_id===A.id&&s.project_id===p.id,'Relación de proyecto incorrecta.');return 'Proyecto/subproyecto creados por API y vinculados a la misma empresa.';});
 await run(14,async()=>{if(!browser)throw new Blocked('Navegador no disponible.');const page=await browser.newPage();await page.addInitScript(token=>sessionStorage.setItem('erp.session',JSON.stringify({access_token:token,refresh_token:'unused',expires_in:3600})),finance.token);await page.goto(base+'/app/cost-centers');await page.getByRole('button',{name:'Importar Excel / CSV'}).click();for(const ext of ['csv','xlsx']){let buffer:Buffer;if(ext==='csv')buffer=Buffer.from(`company_code,code,name\n${A.code},${tag}_CSV,Centro CSV DEV`);else{const w=new ExcelJS.Workbook();w.addWorksheet('CECO').addRows([['company_code','code','name'],[A.code,tag+'_XLSX','Centro XLSX DEV']]);buffer=Buffer.from(await w.xlsx.writeBuffer());}await page.locator('input[type=file]').setInputFiles({name:'verificacion.'+ext,mimeType:ext==='csv'?'text/csv':'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',buffer});await page.getByRole('button',{name:'Validar y previsualizar'}).click();await page.getByText('Vista previa · sin escrituras',{exact:false}).waitFor();check(await page.getByRole('button',{name:'Confirmar importación del lote'}).count()===1,'Importación de archivo tiene errores.');}await page.close();return 'CSV y XLSX leídos por worker del frontend; ambos previsualizados mediante RPC real, sin mocks.';});
 const rows=()=>[{company_code:A.code,code:tag+'_IMPORT_CHILD',name:'Importado hijo',parent_code:tag+'_IMPORT_ROOT',active:true},{company_code:A.code,code:tag+'_IMPORT_ROOT',name:'Importado raíz',active:true}];
 await run(15,async()=>{const before=(await list('/cost-centers?company_id='+A.id,finance.token)).length;const audits=(await ok('/audit?company_id='+A.id+'&limit=1')).count;const r=await ok('/cost-centers/import','POST',{company_id:A.id,rows:rows(),commit:false},finance.token);check(!r.committed&&r.created===2&&r.errors.length===0,'Preview no válido.');check((await list('/cost-centers?company_id='+A.id,finance.token)).length===before,'Preview persistió centros.');check((await ok('/audit?company_id='+A.id+'&limit=1')).count===audits,'Preview persistió auditoría.');return 'Preview de hijo antes de padre: 2 previstos, 0 escrituras y 0 eventos persistidos (comparación antes/después).';});
 await run(16,async()=>{const r=await ok('/cost-centers/import','POST',{company_id:A.id,rows:rows(),commit:true},finance.token);check(r.committed&&r.created===2&&!r.errors.length,'Lote no confirmado.');return 'Lote confirmado: 2 creados y 0 errores en Supabase DEV.';});
 await run(17,async()=>{const r=await ok('/cost-centers/import','POST',{company_id:A.id,rows:rows(),commit:true},finance.token);check(r.committed&&r.created===0&&r.ignored===2&&!r.errors.length,'Repetición no idempotente.');return 'Mismo lote: 0 creados, 2 ignorados, 0 errores.';});
 await run(18,async()=>{await ok(`/users/${solicitante.id}/status`,'PUT',{status:'blocked'});try{const r=await api('/auth/me','GET',undefined,solicitante.token);check(r.status===403,'JWT anterior al bloqueo no rechazado.');const direct=await rest('cost_centers?company_id=eq.'+A.id,'GET',undefined,solicitante.token);check(direct.status===200&&direct.data.length===0,'REST permite lectura a perfil bloqueado.');}finally{await ok(`/users/${solicitante.id}/status`,'PUT',{status:'active'});}return 'Mismo JWT: API 403 y REST sin filas tras bloqueo. Usuario sintético reactivado al concluir.';});
 await run(19,async()=>{await ok(`/users/${solicitante.id}/companies`,'PUT',{company_id:A.id,active:false});try{const r=await api('/auth/me?company_id='+A.id,'GET',undefined,solicitante.token);check(r.status===403,'Membership revocada aún autoriza API.');const direct=await rest('cost_centers?company_id=eq.'+A.id,'GET',undefined,solicitante.token);check(direct.status===200&&direct.data.length===0,'Membership revocada aún autoriza REST.');}finally{await ok(`/users/${solicitante.id}/companies`,'PUT',{company_id:A.id,active:true});}return 'Mismo JWT: API 403 y REST sin filas tras revocación; membresía de prueba restaurada.';});
 await run(20,async()=>{const read=await rest('cost_centers?company_id=eq.'+B.id,'GET',undefined,solicitante.token);check(read.status===200&&read.data.length===0,'REST filtra mal empresa B.');const write=await rest('cost_centers','POST',{company_id:A.id,code:tag+'_DIRECT',name:'Debe rechazarse'},finance.token);check(write.status===403,'REST directo permite INSERT.');const audit=await rest('audit_logs','POST',{action:'forged',category:'administration'},finance.token);check(audit.status===403,'REST permite insertar auditoría arbitraria.');return 'REST: B devuelve 0 filas; INSERT directo de maestro y auditoría devuelve 403.';});
 await run(21,async()=>{const q=await ok('/audit?company_id='+A.id+'&entity_type=cost_centers&limit=100');check(q.data.some((r:any)=>r.user_id===finance.id&&r.company_id===A.id&&r.action==='insert'&&r.new_values?.id===root.id),'Falta evento esperado con actor/empresa.');return 'Auditoría consultada por API: actor Finanzas sintético, empresa A, entidad CECO y new_values correctos.';});
 await run(22,async()=>{throw new Blocked('No hay buzón SMTP verificable en esta sesión. No se envió correo a direcciones ajenas; respuesta HTTP o token generado por Auth Admin no acreditan entrega SMTP/callback.');});
 await run(23,async()=>{const secrets=[config.SUPABASE_SECRET_KEY,process.env.SUPABASE_DB_URL].filter(Boolean);for(const rootDir of ['src/client','src/shared','dist/client'])for(const entry of await readdir(rootDir,{recursive:true,withFileTypes:true})){if(!entry.isFile())continue;const s=await readFile(entry.parentPath+'/'+entry.name,'utf8');check(!secrets.some(secret=>s.includes(secret!)),'Credencial encontrada en frontera cliente.');check(!/SUPABASE_SECRET_KEY|sb_secret_/.test(s),'Referencia secreta encontrada en cliente.');}for(const entry of await readdir('.tools',{withFileTypes:true})){if(entry.isFile()&&/\.(log|err)$/.test(entry.name)){const s=await readFile('.tools/'+entry.name,'utf8');check(!secrets.some(secret=>s.includes(secret!)),'Credencial encontrada en logs locales.');}}return 'Valores reales comparados en memoria: ausentes en src/client, shared, bundle y logs locales disponibles. No se exportaron valores ni respuestas Auth.';});
}catch(e){for(const r of results)if(r.evidence==='Dependencia todavía no verificada.')r.evidence=e instanceof Blocked?e.message:'Dependencia de ejecución fallida; detalle sensible omitido.';console.log('Ejecución detenida; informe sanitizado guardado.');}
finally{await persist();if(browser)await browser.close().catch(()=>{});if(server)await new Promise<void>(resolve=>server.close(()=>resolve()));if(sql)await sql.end().catch(()=>{});console.log('Matriz guardada. Fase 4 no iniciada.');}
