begin;
-- Minimal currency labels follow the authorized report; no catalog grants.
create or replace function public.treasury_cashflow(target_company uuid) returns jsonb language plpgsql stable security definer set search_path='' as $$
#variable_conflict use_column
 begin
 perform private.finance_require('cashflow.view',target_company);
 return jsonb_build_object('currencies',(select coalesce(jsonb_agg(jsonb_build_object('id',id,'name',code)),'[]') from public.currencies),'actual',(select coalesce(jsonb_agg(x),'[]') from (select transaction_date,currency_id,sum(case transaction_type when 'credit' then amount else -amount end) amount from public.bank_transactions where company_id=target_company and evidence_state='confirmed' group by transaction_date,currency_id)x),'committed',(select coalesce(jsonb_agg(x),'[]') from (select p.due_date,p.currency_id,sum(p.outstanding_amount) amount from public.payables p where p.company_id=target_company and p.status='approved' and p.outstanding_amount>0 group by p.due_date,p.currency_id)x),'forecast','[]'::jsonb,'position',(select coalesce(jsonb_agg(x),'[]') from (select a.id,a.display_name,a.currency_id,a.opening_date,case when a.opening_balance is null then null else a.opening_balance+coalesce((select sum(case t.transaction_type when 'credit' then t.amount else -t.amount end) from public.bank_transactions t where t.bank_account_id=a.id and t.evidence_state='confirmed' and t.transaction_date>=a.opening_date),0) end recorded_position,'Posición registrada; cobertura de extracto no garantizada' as qualification from public.company_bank_accounts a where a.company_id=target_company)x));end $$;
create or replace function public.treasury_dashboard(target_company uuid) returns jsonb language plpgsql stable security definer set search_path='' as $$
#variable_conflict use_column
 begin
 perform private.finance_require('payment_order.view',target_company);
 return jsonb_build_object('currencies',(select coalesce(jsonb_agg(jsonb_build_object('id',id,'name',code)),'[]') from public.currencies),'approved_payables',case when private.has_permission('payable.view',target_company) then (select coalesce(jsonb_agg(x),'[]') from (select due_date,currency_id,sum(outstanding_amount) amount from public.payables where company_id=target_company and status='approved' and outstanding_amount>0 group by due_date,currency_id)x) end,'schedule',(select coalesce(jsonb_agg(x),'[]') from (select o.id,o.payment_order_number,s.legal_name as beneficiary,o.requested_payment_date,o.scheduled_payment_date,o.currency_id,o.status,(select string_agg(distinct r.priority,', ') from public.payment_order_items i join public.payables p on p.id=i.payable_id join public.financial_requests r on r.id=p.request_id where i.payment_order_id=o.id) as priority,a.display_name as bank,o.total_amount-coalesce((select sum(p.amount) from public.payments p where p.payment_order_id=o.id and p.status='executed'),0) as outstanding_amount,(select min(p.due_date) from public.payment_order_items i join public.payables p on p.id=i.payable_id where i.payment_order_id=o.id) due_date from public.payment_orders o join public.suppliers s on s.id=o.beneficiary_id left join public.company_bank_accounts a on a.id=o.bank_account_id where o.company_id=target_company and o.status in ('submitted','under_review','approved','scheduled','partially_paid') order by coalesce(o.scheduled_payment_date,o.requested_payment_date) limit 500)x),'payments_unreconciled',case when private.has_permission('payment.view',target_company) then (select count(*) from public.payments p where p.company_id=target_company and p.status='executed' and p.amount>coalesce((select sum(m.amount) from public.bank_reconciliation_matches m where m.payment_id=p.id and m.status='reconciled'),0)) end,'bank_unreconciled',case when private.has_permission('bank_transaction.view',target_company) then (select count(*) from public.bank_transactions where company_id=target_company and evidence_state='confirmed' and status not in ('reconciled','excluded')) end,'batches_pending',case when private.has_permission('payment_batch.view',target_company) then (select count(*) from public.payment_batches where company_id=target_company and status not in ('completed','cancelled')) end);end $$;
commit;
