begin;
insert into public.permissions(module,resource,action,code,description,requires_company,scope,is_sensitive)
select 'tesoreria',r,a,r||'.'||a,r||': '||a,true,'none',r||'.'||a in ('payment_order.approve','payment.execute','payment.reverse','payment_batch.approve','bank_reconciliation.close','bank_reconciliation.reopen')
from (values ('bank','view create edit disable'),('payment_order','view create edit submit approve observe reject cancel'),('payment','view schedule execute reverse'),('payment_batch','view create submit approve cancel'),('bank_transaction','view import create_manual'),('bank_reconciliation','view match reconcile close reopen'),('cashflow','view manage_projection')) v(r,actions) cross join lateral unnest(string_to_array(actions,' ')) a
on conflict(code) do update set active=true,is_sensitive=public.permissions.is_sensitive or excluded.is_sensitive;
create table public.banks (
 id uuid primary key default gen_random_uuid(),company_id uuid not null references public.companies(id),code text not null,name text not null,country_code text not null default 'PE',active boolean not null default true,created_at timestamptz not null default now(),unique(company_id,id),unique(company_id,code));
create table public.company_bank_accounts (
 id uuid primary key default gen_random_uuid(),company_id uuid not null references public.companies(id),bank_id uuid not null,currency_id uuid not null references public.currencies(id),account_number text not null check(account_number ~ '^[0-9A-Za-z-]{6,40}$'),cci text check(cci ~ '^[0-9]{20}$'),account_type text not null default 'checking',display_name text not null,
 opening_balance numeric(18,2),opening_date date,active boolean not null default true,valid_from date not null default current_date,valid_to date,created_by uuid not null references public.profiles(id),updated_by uuid not null references public.profiles(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(company_id,id),unique(company_id,bank_id,account_number,currency_id),foreign key(company_id,bank_id) references public.banks(company_id,id),check((opening_balance is null)=(opening_date is null)),check(valid_to is null or valid_to>=valid_from));
create table public.payment_methods (
 id uuid primary key default gen_random_uuid(),company_id uuid not null references public.companies(id),code text not null,name text not null,requires_beneficiary_account boolean not null default true,active boolean not null default true,created_at timestamptz not null default now(),unique(company_id,id),unique(company_id,code));
create table public.payment_orders (
 id uuid primary key default gen_random_uuid(),company_id uuid not null references public.companies(id),payment_order_number text not null,beneficiary_type text not null default 'supplier' check(beneficiary_type='supplier'),beneficiary_id uuid not null,currency_id uuid not null references public.currencies(id),bank_account_id uuid,beneficiary_account_id uuid,payment_method_id uuid not null,requested_payment_date date not null,scheduled_payment_date date,description text not null,total_amount numeric(18,2) not null check(total_amount>0),status text not null default 'draft' check(status in ('draft','submitted','under_review','approved','scheduled','partially_paid','paid','observed','rejected','cancelled')),version integer not null default 1,
 created_by uuid not null references public.profiles(id),submitted_by uuid references public.profiles(id),approved_by uuid references public.profiles(id),approved_at timestamptz,cancelled_by uuid references public.profiles(id),cancelled_at timestamptz,cancellation_reason text,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(company_id,id),unique(company_id,payment_order_number),foreign key(company_id,beneficiary_id) references public.supplier_companies(company_id,supplier_id),foreign key(company_id,bank_account_id) references public.company_bank_accounts(company_id,id),foreign key(company_id,beneficiary_account_id) references public.supplier_bank_accounts(company_id,id),foreign key(company_id,payment_method_id) references public.payment_methods(company_id,id),check(approved_by is null or approved_by<>created_by));
create table public.payment_order_items (
 id uuid primary key default gen_random_uuid(),company_id uuid not null,payment_order_id uuid not null,payable_id uuid not null,amount_to_pay numeric(18,2) not null check(amount_to_pay>0),unique(company_id,id),unique(payment_order_id,payable_id),foreign key(company_id,payment_order_id) references public.payment_orders(company_id,id),foreign key(company_id,payable_id) references public.payables(company_id,id));
create table public.payment_batches (
 id uuid primary key default gen_random_uuid(),company_id uuid not null references public.companies(id),batch_number text not null,currency_id uuid not null references public.currencies(id),description text not null,total_amount numeric(18,2) not null check(total_amount>0),individual_approval_required boolean not null default true,status text not null default 'draft' check(status in ('draft','submitted','approved','processing','partially_completed','completed','cancelled')),created_by uuid not null references public.profiles(id),approved_by uuid references public.profiles(id),approved_at timestamptz,created_at timestamptz not null default now(),unique(company_id,id),unique(company_id,batch_number),check(approved_by is null or approved_by<>created_by));
create table public.payment_batch_items (
 id uuid primary key default gen_random_uuid(),company_id uuid not null,batch_id uuid not null,payment_order_id uuid not null,unique(company_id,id),unique(batch_id,payment_order_id),foreign key(company_id,batch_id) references public.payment_batches(company_id,id),foreign key(company_id,payment_order_id) references public.payment_orders(company_id,id));
create table public.payments (
 id uuid primary key default gen_random_uuid(),company_id uuid not null,payment_number text not null,payment_order_id uuid not null,bank_account_id uuid not null,beneficiary_type text not null default 'supplier' check(beneficiary_type='supplier'),beneficiary_id uuid not null,payment_date date not null,currency_id uuid not null references public.currencies(id),amount numeric(18,2) not null check(amount>0),payment_method_id uuid not null,operation_number text not null check(length(trim(operation_number)) between 1 and 100),reference text,status text not null default 'draft' check(status in ('draft','executed','reversed','cancelled')),created_by uuid not null references public.profiles(id),executed_by uuid references public.profiles(id),executed_at timestamptz,reversed_by uuid references public.profiles(id),reversed_at timestamptz,reversal_reason text,created_at timestamptz not null default now(),unique(company_id,id),unique(company_id,payment_number),foreign key(company_id,payment_order_id) references public.payment_orders(company_id,id),foreign key(company_id,bank_account_id) references public.company_bank_accounts(company_id,id),foreign key(company_id,beneficiary_id) references public.supplier_companies(company_id,supplier_id),foreign key(company_id,payment_method_id) references public.payment_methods(company_id,id));
create unique index payment_operation_unique on public.payments(bank_account_id,payment_date,operation_number) where status<>'cancelled';
create table public.payment_allocations (
 id uuid primary key default gen_random_uuid(),company_id uuid not null,payment_id uuid not null,payable_id uuid not null,allocated_amount numeric(18,2) not null check(allocated_amount>0),unique(company_id,id),unique(payment_id,payable_id),foreign key(company_id,payment_id) references public.payments(company_id,id),foreign key(company_id,payable_id) references public.payables(company_id,id));
alter table public.payables drop constraint payables_check;
alter table public.payables add column allocated_paid_amount numeric(18,2) not null default 0;
alter table public.payables add column payment_status text generated always as (case when outstanding_amount=0 then 'paid' when allocated_paid_amount>0 then 'partially_paid' else 'unpaid' end) stored;
alter table public.payables add constraint payable_derived_balance check(allocated_paid_amount>=0 and allocated_paid_amount<=original_amount and outstanding_amount=original_amount-allocated_paid_amount);
create table public.bank_import_batches (
 id uuid primary key default gen_random_uuid(),company_id uuid not null,bank_account_id uuid not null,source_filename text not null,source_hash text not null,column_mapping jsonb not null,row_count integer not null,created_by uuid not null references public.profiles(id),created_at timestamptz not null default now(),unique(company_id,id),unique(bank_account_id,source_hash),foreign key(company_id,bank_account_id) references public.company_bank_accounts(company_id,id));
create table public.bank_transactions (
 id uuid primary key default gen_random_uuid(),company_id uuid not null,bank_account_id uuid not null,transaction_date date not null,value_date date,transaction_type text not null check(transaction_type in ('debit','credit')),amount numeric(18,2) not null check(amount>0),currency_id uuid not null references public.currencies(id),bank_reference text not null,description text not null,counterparty text,source text not null check(source in ('manual','import','payment','reversal')),evidence_state text not null check(evidence_state in ('expected','confirmed')),external_id text,exclusion_reason text,payment_id uuid,import_batch_id uuid,status text not null default 'unmatched' check(status in ('unmatched','partially_matched','matched','reconciled','excluded')),created_by uuid not null references public.profiles(id),created_at timestamptz not null default now(),unique(company_id,id),foreign key(company_id,bank_account_id) references public.company_bank_accounts(company_id,id),foreign key(company_id,payment_id) references public.payments(company_id,id),foreign key(company_id,import_batch_id) references public.bank_import_batches(company_id,id),check((source in ('payment','reversal') and evidence_state='expected' and payment_id is not null) or (source in ('manual','import') and evidence_state='confirmed' and payment_id is null)));
create unique index bank_external_unique on public.bank_transactions(bank_account_id,external_id) where external_id is not null;
create unique index bank_payment_expected_unique on public.bank_transactions(payment_id,source) where payment_id is not null;
create table public.bank_reconciliation_periods (
 id uuid primary key default gen_random_uuid(),company_id uuid not null,bank_account_id uuid not null,start_date date not null,end_date date not null,status text not null default 'open' check(status in ('open','closed')),created_by uuid not null references public.profiles(id),closed_by uuid references public.profiles(id),closed_at timestamptz,reopened_by uuid references public.profiles(id),reopened_at timestamptz,reopen_reason text,created_at timestamptz not null default now(),unique(company_id,id),foreign key(company_id,bank_account_id) references public.company_bank_accounts(company_id,id),check(end_date>=start_date));
create table public.bank_reconciliation_matches (
 id uuid primary key default gen_random_uuid(),company_id uuid not null,period_id uuid not null,bank_transaction_id uuid not null,payment_id uuid not null,amount numeric(18,2) not null check(amount>0),status text not null default 'matched' check(status in ('matched','reconciled','cancelled')),matched_by uuid not null references public.profiles(id),matched_at timestamptz not null default now(),reconciled_by uuid references public.profiles(id),reconciled_at timestamptz,reason text,unique(company_id,id),foreign key(company_id,period_id) references public.bank_reconciliation_periods(company_id,id),foreign key(company_id,bank_transaction_id) references public.bank_transactions(company_id,id),foreign key(company_id,payment_id) references public.payments(company_id,id));
-- Derived balances cannot be altered through the existing F4 transitions.
create function private.guard_payable_treasury() returns trigger language plpgsql security definer set search_path='' as $$ begin
 if new.company_id<>old.company_id or new.original_amount<>old.original_amount or new.currency_id<>old.currency_id or new.supplier_id<>old.supplier_id then raise exception using errcode='23514',message='Obligation identity immutable'; end if;
 if new.status is distinct from old.status and exists(select 1 from public.payment_order_items i join public.payment_orders o on o.id=i.payment_order_id where i.payable_id=old.id and o.status not in ('cancelled','rejected','draft','observed')) then raise exception using errcode='23514',message='Active payment order protects obligation'; end if;return new;end $$;
create trigger guard_payable_treasury before update on public.payables for each row execute function private.guard_payable_treasury();
-- Same audit trigger, with bank numbers removed in every applicable table.
create or replace function private.audit_finance() returns trigger language plpgsql security definer set search_path='' as $$
declare b jsonb;a jsonb;d jsonb;begin
 if tg_op<>'INSERT' then b:=to_jsonb(old);end if;if tg_op<>'DELETE' then a:=to_jsonb(new);end if;d:=coalesce(a,b);
 if tg_table_name in ('supplier_bank_accounts','supplier_bank_account_changes','company_bank_accounts') then b:=b-array['account_number','cci','proposed'];a:=a-array['account_number','cci','proposed'];end if;
 insert into public.audit_logs(user_id,action,category,entity_type,entity_id,company_id,old_values,new_values) values(auth.uid(),lower(tg_op)||case when a->>'status' is distinct from b->>'status' then '.'||coalesce(a->>'status','deleted') else '' end,'finance',tg_table_name,d->>'id',(d->>'company_id')::uuid,b,a);return coalesce(new,old);end $$;
do $$ declare t text;p text;begin
 for t,p in select * from (values ('banks','bank.view'),('company_bank_accounts','bank.view'),('payment_methods','bank.view'),('payment_orders','payment_order.view'),('payment_order_items','payment_order.view'),('payments','payment.view'),('payment_allocations','payment.view'),('payment_batches','payment_batch.view'),('payment_batch_items','payment_batch.view'),('bank_transactions','bank_transaction.view'),('bank_import_batches','bank_transaction.view'),('bank_reconciliation_periods','bank_reconciliation.view'),('bank_reconciliation_matches','bank_reconciliation.view'))v(t,p) loop
 execute format('alter table public.%I enable row level security',t);execute format('revoke all on public.%I from public,anon,authenticated,service_role',t);execute format('grant select on public.%I to authenticated',t);execute format('create policy treasury_read on public.%I for select to authenticated using(private.has_permission(%L,company_id))',t,p);execute format('create trigger audit_finance after insert or update or delete on public.%I for each row execute function private.audit_finance()',t);end loop;end $$;
commit;
