begin;
create table public.accounting_demo_companies(
 company_id uuid primary key references public.companies(id),designated_by uuid not null references public.profiles(id),designated_at timestamptz not null default now(),reason text not null check(length(trim(reason))between 1 and 2000)
);
alter table public.accounting_demo_companies enable row level security;
revoke all on public.accounting_demo_companies from public,anon,authenticated,service_role;
grant select on public.accounting_demo_companies to authenticated;
create policy accounting_demo_company_read on public.accounting_demo_companies for select to authenticated using(private.has_permission('accounting_configuration.view',company_id));
create function private.guard_demo_company()returns trigger language plpgsql security definer set search_path='' as $$begin
 if tg_op<>'INSERT'then raise exception using errcode='23514',message='DEMO company designation is immutable';end if;return new;end $$;
create trigger guard_demo_company before update or delete on public.accounting_demo_companies for each row execute function private.guard_demo_company();
create function public.accounting_demo_company_designate(target_company uuid,reason text)returns jsonb language plpgsql security definer set search_path='' as $$declare r public.accounting_demo_companies;begin
 perform private.treasury_lock();perform private.finance_require('accounting_configuration.manage',target_company);
 if coalesce(length(trim(reason)),0)not between 1 and 2000 then raise exception using errcode='22023',message='Explicit DEMO company reason required';end if;
 insert into public.accounting_demo_companies(company_id,designated_by,reason)values(target_company,auth.uid(),reason)on conflict(company_id)do nothing returning * into r;
 if r.company_id is null then select * into r from public.accounting_demo_companies where company_id=target_company;if r.reason<>reason then raise exception using errcode='23514',message='Existing DEMO company designation is immutable';end if;end if;
 perform private.accounting_event(target_company,'accounting_configuration',target_company,'demo_company_designated',reason,jsonb_build_object('demo_only',true));return to_jsonb(r);
end $$;
create or replace function public.accounting_demo_configure(target_company uuid,enabled boolean,reason text)returns jsonb language plpgsql security definer set search_path='' as $$declare r public.accounting_feature_flags;begin
 perform private.treasury_lock();perform private.finance_require('accounting_configuration.manage',target_company);
 if enabled is null or coalesce(length(trim(reason)),0)not between 1 and 2000 then raise exception using errcode='22023',message='Explicit demo flag and reason required';end if;
 if enabled and not exists(select 1 from public.accounting_demo_companies where company_id=target_company)then raise exception using errcode='42501',message='Explicit DEMO company designation required';end if;
 insert into public.accounting_feature_flags(company_id,demo_enabled,updated_by)values(target_company,enabled,auth.uid())on conflict(company_id)do update set demo_enabled=excluded.demo_enabled,updated_by=auth.uid(),updated_at=now()returning * into r;
 perform private.accounting_event(target_company,'accounting_configuration',target_company,'demo_configuration',reason,jsonb_build_object('demo_enabled',enabled,'auto_generate',false,'auto_post',false,'production_rules',false));return to_jsonb(r);
end $$;
create or replace function public.accounting_demo_rule_designate(target_id uuid,reason text)returns jsonb language plpgsql security definer set search_path='' as $$declare r public.accounting_rules;begin
 perform private.treasury_lock();select * into r from public.accounting_rules where id=target_id;perform private.finance_require('accounting_configuration.manage',r.company_id);perform private.finance_require('accounting_rule.activate',r.company_id);
 if not exists(select 1 from public.accounting_demo_companies where company_id=r.company_id)or not exists(select 1 from public.accounting_feature_flags where company_id=r.company_id and demo_enabled)or r.code!~'^(DEMO|TEST)[_-]'or r.name!~*'^(DEMO|TEST)[ :_-]'or r.created_by=auth.uid()or coalesce(length(trim(reason)),0)not between 1 and 2000 then raise exception using errcode='23514',message='Explicit DEMO company configuration, labels and independent actor required';end if;
 if exists(select 1 from public.accounting_rule_lines l join public.accounting_accounts a on a.id=l.account_id and a.company_id=l.company_id where l.rule_id=r.id and(a.code!~'^(DEMO|TEST)[_-]'or a.name!~*'^(DEMO|TEST)[ :_-]'))then raise exception using errcode='23514',message='Only explicitly synthetic accounts allowed';end if;
 insert into public.accounting_demo_rules(company_id,rule_id,designated_by)values(r.company_id,r.id,auth.uid())on conflict do nothing;perform private.accounting_event(r.company_id,'rule',r.id,'designate_demo',reason,jsonb_build_object('version',r.version,'production_enabled',false));return jsonb_build_object('rule_id',r.id,'demo',true,'production_enabled',false);
end $$;
create or replace function public.accounting_demo_dashboard(target_company uuid)returns jsonb language plpgsql stable security definer set search_path='' as $$begin
 perform private.finance_require('demo_dashboard.view',target_company);if not exists(select 1 from public.accounting_demo_companies where company_id=target_company)or not exists(select 1 from public.accounting_feature_flags where company_id=target_company and demo_enabled and not auto_generate and not auto_post and not production_rules)then raise exception using errcode='42501',message='DEMO dashboard disabled for company';end if;
 return jsonb_build_object('payables_outstanding',(select coalesce(jsonb_agg(x order by x.currency_code),'[]')from(select c.code currency_code,sum(p.outstanding_amount) amount from public.payables p join public.currencies c on c.id=p.currency_id where p.company_id=target_company and p.status='approved'and p.outstanding_amount>0 group by c.code)x),'receivables_outstanding',(select coalesce(jsonb_agg(x order by x.currency_code),'[]')from(select c.code currency_code,sum(r.original_amount-coalesce((select sum(a.amount)from public.collection_allocations a where a.receivable_id=r.id and a.status='valid'),0)) amount from public.receivables r join public.currencies c on c.id=r.currency_id where r.company_id=target_company and r.status='active' group by c.code)x),'upcoming_payments',(select coalesce(jsonb_agg(x order by x.due_date),'[]')from(select p.due_date,c.code currency_code,sum(p.outstanding_amount) amount from public.payables p join public.currencies c on c.id=p.currency_id where p.company_id=target_company and p.status='approved'and p.outstanding_amount>0 and p.due_date between current_date and current_date+30 group by p.due_date,c.code limit 100)x),'collections',(select coalesce(jsonb_agg(x order by x.currency_code),'[]')from(select c.code currency_code,sum(a.amount) amount from public.collection_allocations a join public.collections n on n.id=a.collection_id and n.status='active' join public.currencies c on c.id=n.currency_id where a.company_id=target_company and a.status='valid'group by c.code)x),'registered_bank',(select coalesce(jsonb_agg(x order by x.currency_code),'[]')from(select c.code currency_code,sum(case t.transaction_type when 'credit'then t.amount else -t.amount end) amount from public.bank_transactions t join public.currencies c on c.id=t.currency_id where t.company_id=target_company and t.evidence_state='confirmed'group by c.code)x),'travel_pending',(select count(*)from public.travel_expense_requests where company_id=target_company and status not in('closed','cancelled','rejected')),'accounting_pending',(select count(*)from public.accounting_events where company_id=target_company and workflow_status in('pending_mapping','ready','previewed','error')),'journals_posted',(select count(*)from public.journal_entries where company_id=target_company and status in('posted','reversed')),'open_period',(select jsonb_build_object('year',year,'month',month,'start_date',start_date,'end_date',end_date)from public.accounting_periods where company_id=target_company and status='open'order by start_date desc limit 1));
end $$;
revoke all on function private.guard_demo_company()from public,anon,authenticated,service_role;
revoke all on function public.accounting_demo_company_designate(uuid,text)from public,anon,service_role;
grant execute on function public.accounting_demo_company_designate(uuid,text)to authenticated;
commit;
